[project]
name = "example"
telemetry = false
cache_dir = "./.cache"

[[project.requirements]]
contract_id = 'SP4SZE494VC2YC5JYG7AYFQ44F5Q4PYV7DVMDPBG.ststx-token'

[[project.requirements]]
contract_id = 'SP4SZE494VC2YC5JYG7AYFQ44F5Q4PYV7DVMDPBG.sip-010-trait-ft-standard'

[contracts.rendezvous-token]
path = 'contracts/rendezvous-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.cargo]
path = "contracts/cargo.clar"
clarity_version = 3
epoch = 3.0

[contracts.counter]
path = "contracts/counter.clar"
clarity_version = 3
epoch = 3.0

[contracts.reverse]
path = "contracts/reverse.clar"
clarity_version = 3
epoch = 3.0

[contracts.slice]
path = "contracts/slice.clar"
clarity_version = 3
epoch = 3.0

[contracts.ft-transfer-many]
path = 'contracts/ft-transfer-many.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
