[project]
name = "example"
telemetry = false
cache_dir = "./.cache"

[contracts.cargo]
path = "contracts/cargo.clar"

[contracts.counter]
path = "contracts/counter.clar"

[contracts.reverse]
path = "contracts/reverse.clar"

[contracts.slice]
path = "contracts/slice.clar"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
